# Generated by Django 3.2.16 on 2023-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractionimagemodel",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="опубликовано"
            ),
        ),
    ]
