# Generated by Django 3.2.16 on 2023-03-04 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите имя",
                        max_length=150,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(default="DEFAULT", max_length=150),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="слаг",
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="слаг категории",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Укажите вес категории",
                        verbose_name="вес категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите имя",
                        max_length=150,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(default="DEFAULT", max_length=150),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="слаг",
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="слаг тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="опубликовано"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите имя",
                        max_length=150,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(default="DEFAULT", max_length=150),
                ),
                (
                    "text",
                    models.TextField(
                        default="Превосходно и роскошно",
                        help_text="Опишите товар",
                        validators=[
                            core.validators.custom_validator(
                                "превосходно", "роскошно"
                            )
                        ],
                        verbose_name="описание товара",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to="catalog/preview",
                        verbose_name="будет приведено к размеру 300x300",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_items",
                        to="catalog.category",
                        verbose_name="каталог",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        to="catalog.Tag", verbose_name="теги"
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.CreateModel(
            name="GalleryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/gallery",
                        verbose_name="будет приведено к размеру 300x300",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="catalog.item",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "галерея",
                "verbose_name_plural": "галерея",
            },
        ),
    ]
