# Generated by Django 3.2.16 on 2023-02-22 15:47

import django.core.validators
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="Превосходное описание роскошного товара!",
                help_text="Опишите товар",
                validators=[catalog.models.custom_validator],
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                default="Гениальное наименование роскошного товара!",
                help_text="Назовите товар",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Наименование",
            ),
        ),
    ]
