# Generated by Django 3.2.16 on 2023-02-22 16:38

import django.core.validators
from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_auto_20230222_2047"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Скройте или опубликуйте товар",
                        verbose_name="Товар опубликован?",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        default="Акция",
                        help_text="Назовите тег",
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Наименование тега",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Роскошный и превосходный текст про тег",
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Название тега",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Скройте или опубликуйте товар",
                verbose_name="Товар опубликован?",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                default="Гениальное наименование роскошного товара!",
                help_text="Назовите товар",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Наименование товара",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="Превосходное описание роскошного товара!",
                help_text="Опишите товар",
                validators=[catalog.models.custom_validator],
                verbose_name="Описание товара",
            ),
        ),
    ]
