# Generated by Django 3.2.16 on 2023-03-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('catalog', '0002_imagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('abstractionimagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.abstractionimagemodel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='catalog.item', verbose_name='товар')),
            ],
            bases=('core.abstractionimagemodel',),
        ),
        migrations.CreateModel(
            name='MainImageModel',
            fields=[
                ('abstractionimagemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.abstractionimagemodel')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.item', verbose_name='превью')),
            ],
            bases=('core.abstractionimagemodel',),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
