# Generated by Django 3.2.16 on 2023-02-22 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_auto_20230222_2138"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Скройте или опубликуйте категорию",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Назовите категорию",
                        validators=[
                            django.core.validators.MaxLengthValidator(150)
                        ],
                        verbose_name="Наименование категории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Роскошный и превосходный текст про категорию",
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(200)
                        ],
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Укажите вес категории",
                        verbose_name="Вес категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Скройте или опубликуйте товар",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Скройте или опубликуйте тег",
                verbose_name="Опубликовано",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="Назовите тег",
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Наименование тега",
            ),
        ),
    ]
