# Generated by Django 3.2.16 on 2023-03-12 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_auto_20230312_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerymodel",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_items",
                related_query_name="gallery_items",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
    ]
