# Generated by Django 3.2.16 on 2023-02-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_auto_20230222_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(to="catalog.Tag"),
        ),
    ]
