# Generated by Django 3.2.16 on 2023-02-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_item_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalog_items",
                to="catalog.category",
            ),
            preserve_default=False,
        ),
    ]
