# Generated by Django 3.2.16 on 2023-02-24 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_item_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "тег", "verbose_name_plural": "теги"},
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Роскошный и превосходный текст про категорию",
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Название категории",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Наименование"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="Опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Наименование"
            ),
        ),
    ]
