# Generated by Django 3.2.16 on 2023-02-24 20:14

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_auto_20230224_1918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="Превосходно",
                help_text="Опишите товар",
                validators=[core.models.custom_validator],
                verbose_name="Описание товара",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("name",)},
        ),
    ]
