# Generated by Django 3.2.16 on 2023-02-24 21:07

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0011_auto_20230225_0206"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="Превосходно и роскошно",
                help_text="Опишите товар",
                validators=[core.models.custom_validator],
                verbose_name="Описание товара",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="canonical_name",
            field=models.CharField(
                default="ABOBA",
                help_text="АБОБА",
                max_length=150,
                unique=True,
                verbose_name="секретное имя",
            ),
        ),
    ]
