# Generated by Django 3.2.16 on 2023-02-24 21:14

import django.core.validators
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0014_auto_20230225_0209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="Превосходно и роскошно",
                help_text="Опишите товар",
                validators=[core.models.custom_validator],
                verbose_name="Описание товара",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="canonical_name",
            field=models.CharField(
                default="ABOBA",
                help_text="АБОБА",
                max_length=150,
                verbose_name="секретное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Назовите тег",
                validators=[django.core.validators.MaxLengthValidator(200)],
                verbose_name="Название тега",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("canonical_name", "slug", "name")},
        ),
    ]
