# Generated by Django 3.2.16 on 2023-02-26 10:41

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20230225_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Укажите имя', max_length=150, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Назовите категорию', unique=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, help_text='Укажите вес категории', verbose_name='вес категории'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Укажите имя', max_length=150, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='Превосходно и роскошно', help_text='Опишите товар', validators=[core.models.custom_validator], verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Укажите имя', max_length=150, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Назовите тег', unique=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='название тега'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='canonical_name',
        ),
    ]
