# Generated by Django 3.2.16 on 2023-02-26 11:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0026_auto_20230226_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                default="Превосходно и роскошно",
                help_text="Опишите товар",
                validators=[
                    core.models.custom_validator("превосходно", "роскошно")
                ],
                verbose_name="описание товара",
            ),
        ),
    ]
