name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/test_req.txt
        pip install -r requirements/main_req.txt
        pip install -r requirements/dev_req.txt 


  lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: black Lint
        uses: psf/black@stable

      - name: flake8 import Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-absolute-import==1.0.0.1"

      - name: flake8 alphabetize Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-alphabetize==0.0.19"

      - name: flake8 functions names Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-functions-names==0.4.0"

      - name: flake8 variables names Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-variables-names==0.0.5"

      - name: flake8 quotes Lint
        uses: py-actions/flake8@v2
        with:
          plugins: "flake8-quotes==3.3.2"
